// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"go-chat/app/group/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/group/create",
				Handler: CreateGroupHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/group/join",
				Handler: JoinGroupHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/group/getJoinGroupList",
				Handler: GetJoinGroupListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/group/getGroupMemberList",
				Handler: GetGroupMemberListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/group/quit",
				Handler: QuitGroupHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/group/setGroupMemberPermission",
				Handler: SetGroupMemberPermissionHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/group/modifyRemark",
				Handler: ModifyRemarkHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/group/dissolveGroup",
				Handler: DissolveGroupHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/group/getGroupInfo",
				Handler: GetGroupInfoHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
